#!/usr/bin/env bash
set -euo pipefail
: "${API_VER:=2022-11-28}"

# Require provenance label early (even if provided as empty string)
if [ -z "${PROV_LABEL:-}" ]; then
  echo "Missing required PROV_LABEL (provenance label, e.g., AI_CODING_ASSISTANT)" >&2
  exit 1
fi

# TOKEN must be set by the caller
api_get() {
  curl -fsS \
    -H "Authorization: token ${TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: ${API_VER}" \
    "$1"
}

# TOKEN must be set by the caller
api_post() {
  local url="$1" data="$2"
  curl -fsS -X POST \
    -H "Authorization: token ${TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: ${API_VER}" \
    -H "Content-Type: application/json" \
    --data "${data}" \
    "${url}"
}

# ACTOR should be set by the caller (for attribution only)
provenance_block() {
  local pvt
  local normalized_label

  # Normalize label: trim whitespace and convert to lowercase
  normalized_label="$(echo "${PROV_LABEL}" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"

  if [ "$normalized_label" = "human" ]; then
    # Human block - no AI-PROVENANCE comment, no "Generated by" line
    pvt="$(cat <<'EOF'
<blockquote>
  <sub><b>Initiated by:</b>&nbsp;@__ACTOR__</sub>
</blockquote>
EOF
)"
  else
    # Default AI block - includes AI-PROVENANCE comment
    pvt="$(cat <<'EOF'
<!-- AI-PROVENANCE: DO NOT EDIT -->
<blockquote>
  <sub><b>Generated by:</b>&nbsp;__LABEL__<br>
  <b>Initiated by:</b>&nbsp;@__ACTOR__</sub>
</blockquote>
EOF
)"
  fi

  pvt="${pvt/__ACTOR__/${ACTOR:-unknown}}"
  pvt="${pvt/__LABEL__/${PROV_LABEL}}"
  printf '%s' "$pvt"
}